"""命令分组与命令库数据。"""

COMMAND_GROUPS = {
    "环境识别": [
        "📋 快速自查",
        "🐧 Linux 探测",
        "🪟 Windows 探测",
        "☸️ K8s API 探测",
    ],
    "K8s": [
        "🌳 资源浏览", "🔍 查看资源", "🔑 权限与身份", "📋 详情与日志", "🚪 进入容器",
        "🔎 容器内自查", "⚙️ 配置检查", "🌐 网络", "⚠️ 提权与利用",
    ],
    "云平台": [
        "☁️ AWS (亚马逊云)", "🟢 GCP (谷歌云)", "🚀 Cloud Run / Knative",
        "🟠 阿里云", "🔵 腾讯云",
        "🔴 华为云", "🔷 Azure (微软云)", "🟡 百度云", "🟣 Oracle OCI",
        "🌊 DigitalOcean", "🟩 Linode", "⚡ Vultr", "🔶 IBM Cloud",
        "🟤 金山云", "🔹 UCloud", "🛒 京东云", "🌋 火山引擎",
        "☁️ 青云 QingCloud", "🏗️ OpenStack",
    ],
}


def _meta_cmd(name, desc, curl, exec_mode="curl", tags=None):
    return {"name": name, "desc": desc, "tags": tags or ["cloud"],
            "exec": exec_mode, "kubectl": curl, "curl": curl}


def _k8s(name, desc, kubectl, curl, tags=None, exec_mode="both"):
    return {"name": name, "desc": desc, "tags": tags or ["k8s_conn"],
            "exec": exec_mode, "kubectl": kubectl, "curl": curl}

COMMANDS = [{'category': '📋 快速自查',
  'items': [{'name': '本地容器环境自查',
             'desc': 'Docker/K8s 路径与关键变量（首选）',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'echo "=== 容器标志 ===" && (test -f /.dockerenv && echo IN_DOCKER || echo NOT_DOCKER) && '
                        'echo "=== SA ===" && ls -la /var/run/secrets/kubernetes.io/serviceaccount/ 2>/dev/null || echo NO_SA && '
                        'echo "=== 云/K8s 变量 ===" && env | grep -iE '
                        "'^(K_|KUBERNETES_|AWS_|ECS_|GOOGLE_|GCP_|AZURE_|ALIBABA_|TENCENT|HUAWEI|VERCEL|NEXT_|POD_|HOSTNAME)' | sort",
             'curl': 'echo "=== 容器标志 ===" && (test -f /.dockerenv && echo IN_DOCKER || echo NOT_DOCKER) && '
                     'echo "=== SA ===" && ls -la /var/run/secrets/kubernetes.io/serviceaccount/ 2>/dev/null || echo NO_SA && '
                     'echo "=== 云/K8s 变量 ===" && env | grep -iE '
                     "'^(K_|KUBERNETES_|AWS_|ECS_|GOOGLE_|GCP_|AZURE_|ALIBABA_|TENCENT|HUAWEI|VERCEL|NEXT_|POD_|HOSTNAME)' | sort"},
            {'name': '环境变量全量 dump',
             'desc': 'printenv 后贴回环境识别页',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'printenv | sort',
             'curl': 'printenv | sort'},
            {'name': '敏感变量筛查',
             'desc': 'TOKEN/SECRET/KEY 等',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': "printenv | grep -iE '(TOKEN|SECRET|PASSWORD|KEY|CREDENTIAL|AUTH)' | sed 's/=.*/=***/'",
             'curl': "printenv | grep -iE '(TOKEN|SECRET|PASSWORD|KEY|CREDENTIAL|AUTH)' | sed 's/=.*/=***/'"}]},
 {'category': '🐧 Linux 探测',
  'items': [{'name': '云元数据批量探测',
             'desc': 'curl 各云 IMDS，有返回即在该云',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'echo "[AWS/通用]" && curl -s --max-time 2 http://169.254.169.254/latest/meta-data/ | head -5; '
                        'echo "[阿里云]" && curl -s --max-time 2 http://100.100.100.200/latest/meta-data/ | head -5; '
                        'echo "[腾讯云]" && curl -s --max-time 2 http://metadata.tencentyun.com/latest/meta-data/ | head -5; '
                        "echo \"[GCP]\" && curl -s --max-time 2 -H 'Metadata-Flavor: Google' "
                        'http://metadata.google.internal/computeMetadata/v1/ | head -5; '
                        'echo "[Azure]" && curl -s --max-time 2 -H "Metadata: true" '
                        '"http://169.254.169.254/metadata/instance?api-version=2021-02-01" | head -5; '
                        'echo "[Oracle OCI]" && curl -s --max-time 2 -H "Authorization: Bearer Oracle" '
                        'http://169.254.169.254/opc/v2/instance/ | head -5; '
                        'echo "[IBM Cloud]" && curl -s --max-time 2 http://169.254.169.254/metadata/v1/instance | head -5; '
                        'echo "[火山引擎]" && curl -s --max-time 2 http://100.96.0.96/volcstack/latest/meta-data/ | head -5',
             'curl': 'echo "[AWS/通用]" && curl -s --max-time 2 http://169.254.169.254/latest/meta-data/ | head -5; '
                     'echo "[阿里云]" && curl -s --max-time 2 http://100.100.100.200/latest/meta-data/ | head -5; '
                     'echo "[腾讯云]" && curl -s --max-time 2 http://metadata.tencentyun.com/latest/meta-data/ | head -5; '
                     "echo \"[GCP]\" && curl -s --max-time 2 -H 'Metadata-Flavor: Google' "
                     'http://metadata.google.internal/computeMetadata/v1/ | head -5; '
                     'echo "[Azure]" && curl -s --max-time 2 -H "Metadata: true" '
                     '"http://169.254.169.254/metadata/instance?api-version=2021-02-01" | head -5; '
                     'echo "[Oracle OCI]" && curl -s --max-time 2 -H "Authorization: Bearer Oracle" '
                     'http://169.254.169.254/opc/v2/instance/ | head -5; '
                     'echo "[IBM Cloud]" && curl -s --max-time 2 http://169.254.169.254/metadata/v1/instance | head -5; '
                     'echo "[火山引擎]" && curl -s --max-time 2 http://100.96.0.96/volcstack/latest/meta-data/ | head -5'},
            {'name': 'K8s/容器特征',
             'desc': 'cgroup、挂载、DNS、进程',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'echo "=== cgroup ===" && head -5 /proc/1/cgroup 2>/dev/null; '
                        'echo "=== mount ===" && mount | head -15; '
                        'echo "=== resolv ===" && cat /etc/resolv.conf; '
                        'echo "=== hosts ===" && cat /etc/hosts; '
                        'echo "=== ps ===" && ps aux | head -15',
             'curl': 'echo "=== cgroup ===" && head -5 /proc/1/cgroup 2>/dev/null; '
                     'echo "=== mount ===" && mount | head -15; '
                     'echo "=== resolv ===" && cat /etc/resolv.conf; '
                     'echo "=== hosts ===" && cat /etc/hosts; '
                     'echo "=== ps ===" && ps aux | head -15'},
            {'name': '网络与监听端口',
             'desc': 'ss/netstat + K8s DNS',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'ss -tlnp 2>/dev/null || netstat -tlnp 2>/dev/null; '
                        'echo "=== K8s DNS ===" && (getent hosts kubernetes.default 2>/dev/null || nslookup kubernetes.default 2>/dev/null | head -8)',
             'curl': 'ss -tlnp 2>/dev/null || netstat -tlnp 2>/dev/null; '
                     'echo "=== K8s DNS ===" && (getent hosts kubernetes.default 2>/dev/null || nslookup kubernetes.default 2>/dev/null | head -8)'},
            {'name': 'SA Token 与挂载',
             'desc': 'K8s 服务账号路径',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'ls -la /var/run/secrets/kubernetes.io/serviceaccount/ 2>/dev/null; '
                        'cat /var/run/secrets/kubernetes.io/serviceaccount/token 2>/dev/null | head -c 80; echo',
             'curl': 'ls -la /var/run/secrets/kubernetes.io/serviceaccount/ 2>/dev/null; '
                     'cat /var/run/secrets/kubernetes.io/serviceaccount/token 2>/dev/null | head -c 80; echo'}]},
 {'category': '🪟 Windows 探测',
  'items': [{'name': '云/K8s 环境变量',
             'desc': 'cmd 筛选云平台特征变量',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'set | findstr /i "KUBERNETES AWS AZURE GOOGLE GCP ECS K_SERVICE K_REVISION POD HOSTNAME REGION ALIBABA TENCENT HUAWEI CONTAINER"',
             'curl': 'set | findstr /i "KUBERNETES AWS AZURE GOOGLE GCP ECS K_SERVICE K_REVISION POD HOSTNAME REGION ALIBABA TENCENT HUAWEI CONTAINER"'},
            {'name': '元数据与系统信息',
             'desc': 'IMDS + systeminfo',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'echo === SYSTEM === & systeminfo | findstr /i "OS Name OS Version" & echo === IMDS === & '
                        'curl -s --max-time 2 http://169.254.169.254/latest/meta-data/ 2>nul & '
                        'curl -s --max-time 2 -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/ 2>nul',
             'curl': 'echo === SYSTEM === & systeminfo | findstr /i "OS Name OS Version" & echo === IMDS === & '
                     'curl -s --max-time 2 http://169.254.169.254/latest/meta-data/ 2>nul & '
                     'curl -s --max-time 2 -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/ 2>nul'},
            {'name': '容器与 SA 路径',
             'desc': '检测 K8s SA 挂载与 Docker',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'if exist C:\\var\\run\\secrets\\kubernetes.io\\serviceaccount\\token (echo SA_TOKEN=YES) else (echo SA_TOKEN=NO) & '
                        'if exist C:\\.dockerenv (echo IN_DOCKER=YES) else (echo IN_DOCKER=NO) & '
                        'dir C:\\var\\run\\secrets\\kubernetes.io\\serviceaccount\\ 2>nul',
             'curl': 'if exist C:\\var\\run\\secrets\\kubernetes.io\\serviceaccount\\token (echo SA_TOKEN=YES) else (echo SA_TOKEN=NO) & '
                     'if exist C:\\.dockerenv (echo IN_DOCKER=YES) else (echo IN_DOCKER=NO) & '
                     'dir C:\\var\\run\\secrets\\kubernetes.io\\serviceaccount\\ 2>nul'}]},
 {'category': '☸️ K8s API 探测',
  'items': [{'name': 'K8s API /version',
             'desc': '探测 API Server 版本（需 Token）',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl version --short',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/version'},
            {'name': 'K8s API /healthz',
             'desc': '健康检查端点',
             'tags': ['k8s_conn'],
             'exec': 'curl',
             'kubectl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/healthz',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/healthz'},
            {'name': '读取 SA Token 文件',
             'desc': '从默认路径加载 Token',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'cat /var/run/secrets/kubernetes.io/serviceaccount/token',
             'curl': 'cat /var/run/secrets/kubernetes.io/serviceaccount/token'}]},
 {'category': '🌳 资源浏览',
  'items': [{'name': '刷新资源树',
             'desc': '见「资源浏览」标签页 → 刷新',
             'tags': ['k8s_conn'],
             'exec': 'detect',
             'kubectl': '# 资源浏览标签页',
             'curl': '# 资源浏览标签页'},
            {'name': '列出所有 Pod (JSON)',
             'desc': 'JSON 格式 Pod 列表',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get pods -A -o json',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/api/v1/pods'}]},
 {'category': '⚠️ 提权与利用',
  'items': [{'name': '生成 privileged 宿主机挂载 Pod YAML',
             'desc': '审计检测用（仅授权环境）',
             'tags': ['k8s_conn', 'target'],
             'exec': 'local',
             'kubectl': "printf '%s\\n' 'apiVersion: v1' 'kind: Pod' 'metadata:' '  name: audit-hostmount-{POD}' '  namespace: {NAMESPACE}' 'spec:' '  containers:' '  - name: audit' '    image: busybox' '    command: [sleep,3600]' '    securityContext:' '      privileged: true' '    volumeMounts:' '    - name: host' '      mountPath: /host' '  volumes:' '  - name: host' '    hostPath:' '      path: /' '      type: Directory'",
             'curl': "printf '%s\\n' 'apiVersion: v1' 'kind: Pod' 'metadata:' '  name: audit-hostmount-{POD}' '  namespace: {NAMESPACE}' 'spec:' '  containers:' '  - name: audit' '    image: busybox' '    command: [sleep,3600]' '    securityContext:' '      privileged: true' '    volumeMounts:' '    - name: host' '      mountPath: /host' '  volumes:' '  - name: host' '    hostPath:' '      path: /' '      type: Directory'"},
            {'name': '筛选 privileged Pod',
             'desc': '特权容器列表',
             'tags': ['k8s_conn'],
             'exec': 'kubectl',
             'kubectl': 'kubectl get pods -A -o jsonpath=\'{range .items[*]}{.metadata.namespace}/{.metadata.name}{"\\n"}{end}\' | head -50',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/api/v1/pods'},
            {'name': '筛选 hostNetwork Pod',
             'desc': 'hostNetwork=true 的 Pod',
             'tags': ['k8s_conn'],
             'exec': 'kubectl',
             'kubectl': 'kubectl get pods -A -o wide | grep -i hostnetwork || kubectl get pods -A -o json | grep hostNetwork',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/api/v1/pods'}]},
 {'category': '🔍 查看资源',
  'items': [{'name': '列出所有 Pod',
             'desc': '所有命名空间 Pod',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get pods -A',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/api/v1/pods'},
            {'name': '列出命名空间 Pod',
             'desc': '指定 NS Pod',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get pods -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/pods'},
            {'name': '列出所有 Service',
             'desc': '集群 Service',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get svc -A',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/api/v1/services'},
            {'name': '列出所有命名空间',
             'desc': '枚举 NS',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get namespaces',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces'},
            {'name': '列出命名空间 Secret',
             'desc': 'NS Secret',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get secrets -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/secrets'},
            {'name': '列出集群所有 Secret',
             'desc': '集群 Secret',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get secrets -A',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/api/v1/secrets'},
            {'name': '列出命名空间 ConfigMap',
             'desc': 'NS ConfigMap',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get configmaps -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/configmaps'},
            {'name': '查看 ConfigMap 内容',
             'desc': '单个 CM',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get configmap {CONFIGMAP} -n {NAMESPACE} -o yaml',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/configmaps/{CONFIGMAP}'},
            {'name': '列出所有 Node',
             'desc': '节点列表',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get nodes -o wide',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/api/v1/nodes'},
            {'name': '列出 Deployment',
             'desc': 'NS Deployment',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get deployments -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/apps/v1/namespaces/{NAMESPACE}/deployments'},
            {'name': '列出 StatefulSet',
             'desc': 'NS StatefulSet',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get statefulsets -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/apps/v1/namespaces/{NAMESPACE}/statefulsets'},
            {'name': '列出 DaemonSet',
             'desc': 'NS DaemonSet',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get daemonsets -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/apps/v1/namespaces/{NAMESPACE}/daemonsets'},
            {'name': '列出 Endpoints',
             'desc': 'NS Endpoints',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get endpoints -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/endpoints'},
            {'name': '列出 Ingress',
             'desc': 'NS Ingress',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get ingress -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/networking.k8s.io/v1/namespaces/{NAMESPACE}/ingresses'},
            {'name': '列出 PVC',
             'desc': '持久卷声明',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get pvc -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/persistentvolumeclaims'},
            {'name': '列出 PV',
             'desc': '持久卷',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get pv',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/persistentvolumes'},
            {'name': '列出 ServiceAccount',
             'desc': 'NS SA',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get sa -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/serviceaccounts'},
            {'name': '列出 Jobs',
             'desc': 'NS Jobs',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get jobs -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/batch/v1/namespaces/{NAMESPACE}/jobs'},
            {'name': '列出 CronJobs',
             'desc': 'NS CronJobs',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get cronjobs -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/batch/v1/namespaces/{NAMESPACE}/cronjobs'},
            {'name': '列出 ReplicaSet',
             'desc': 'NS RS',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get rs -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/apps/v1/namespaces/{NAMESPACE}/replicasets'},
            {'name': '列出 HPA',
             'desc': '水平扩缩',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get hpa -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/autoscaling/v2/namespaces/{NAMESPACE}/horizontalpodautoscalers'},
            {'name': '列出 Events (NS)',
             'desc': '事件流',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get events -n {NAMESPACE} --sort-by=.lastTimestamp',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/events'},
            {'name': 'API 资源列表',
             'desc': 'discovery',
             'tags': ['k8s_conn'],
             'exec': 'kubectl',
             'kubectl': 'kubectl api-resources',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/apis'}]},
 {'category': '🔑 权限与身份',
  'items': [{'name': '本地解码 JWT Payload',
             'desc': '纯本地解析 Token',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': '# 点击解析 JWT',
             'curl': '# 点击解析 JWT'},
            {'name': '查看当前权限列表',
             'desc': 'SelfSubjectRulesReview',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl auth can-i --list -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" -X POST '
                     '-H "Content-Type: application/json" '
                     '-d \'{"apiVersion":"authorization.k8s.io/v1","kind":"SelfSubjectRulesReview",'
                     '"spec":{"namespace":"{NAMESPACE}"}}\' '
                     '{APISERVER}/apis/authorization.k8s.io/v1/selfsubjectrulesreviews'},
            {'name': '测试 list secrets 权限',
             'desc': '集群级 Secret 列表',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl auth can-i list secrets --all-namespaces',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" -X POST '
                     '-H "Content-Type: application/json" '
                     '-d \'{"apiVersion":"authorization.k8s.io/v1","kind":"SelfSubjectAccessReview",'
                     '"spec":{"resourceAttributes":{"verb":"list","resource":"secrets"}}}\' '
                     '{APISERVER}/apis/authorization.k8s.io/v1/selfsubjectaccessreviews'},
            {'name': '测试 create pods',
             'desc': '创建 Pod 权限',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl auth can-i create pods -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" -X POST '
                     '-H "Content-Type: application/json" '
                     '-d \'{"apiVersion":"authorization.k8s.io/v1","kind":"SelfSubjectAccessReview",'
                     '"spec":{"resourceAttributes":{"namespace":"{NAMESPACE}","verb":"create","resource":"pods"}}}\' '
                     '{APISERVER}/apis/authorization.k8s.io/v1/selfsubjectaccessreviews'},
            {'name': '测试 patch deployments',
             'desc': 'Patch Deployment',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl auth can-i patch deployments -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" -X POST '
                     '-H "Content-Type: application/json" '
                     '-d \'{"apiVersion":"authorization.k8s.io/v1","kind":"SelfSubjectAccessReview",'
                     '"spec":{"resourceAttributes":{"namespace":"{NAMESPACE}","verb":"patch",'
                     '"resource":"deployments","group":"apps"}}}\' '
                     '{APISERVER}/apis/authorization.k8s.io/v1/selfsubjectaccessreviews'},
            {'name': '查看 RoleBinding',
             'desc': 'NS RoleBinding',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get rolebindings -n {NAMESPACE} -o yaml',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/rbac.authorization.k8s.io/v1/namespaces/{NAMESPACE}/rolebindings'},
            {'name': '查看 ClusterRoleBinding',
             'desc': '集群 RoleBinding',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get clusterrolebindings',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/rbac.authorization.k8s.io/v1/clusterrolebindings'},
            {'name': '查看当前 SA Token',
             'desc': 'whoami 等效',
             'tags': ['k8s_conn'],
             'exec': 'kubectl',
             'kubectl': 'kubectl auth whoami',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/authentication.k8s.io/v1/selfsubjectreviews'},
            {'name': '测试 delete pods',
             'desc': '删除 Pod 权限',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl auth can-i delete pods -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" -X POST '
                     '-H "Content-Type: application/json" '
                     '-d \'{"apiVersion":"authorization.k8s.io/v1","kind":"SelfSubjectAccessReview",'
                     '"spec":{"resourceAttributes":{"namespace":"{NAMESPACE}","verb":"delete","resource":"pods"}}}\' '
                     '{APISERVER}/apis/authorization.k8s.io/v1/selfsubjectaccessreviews'},
            {'name': '测试 get secrets',
             'desc': '读取 Secret',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl auth can-i get secrets -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" -X POST '
                     '-H "Content-Type: application/json" '
                     '-d \'{"apiVersion":"authorization.k8s.io/v1","kind":"SelfSubjectAccessReview",'
                     '"spec":{"resourceAttributes":{"namespace":"{NAMESPACE}","verb":"get","resource":"secrets"}}}\' '
                     '{APISERVER}/apis/authorization.k8s.io/v1/selfsubjectaccessreviews'},
            {'name': '测试 escalate roles',
             'desc': '角色提升',
             'tags': ['k8s_conn', 'target'],
             'exec': 'kubectl',
             'kubectl': 'kubectl auth can-i escalate roles -n {NAMESPACE}',
             'curl': 'kubectl auth can-i escalate roles -n {NAMESPACE}'},
            {'name': '查看 ClusterRole',
             'desc': '集群角色',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get clusterroles',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/rbac.authorization.k8s.io/v1/clusterroles'},
            {'name': '查看 Role (NS)',
             'desc': '命名空间角色',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get roles -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/rbac.authorization.k8s.io/v1/namespaces/{NAMESPACE}/roles'}]},
 {'category': '📋 详情与日志',
  'items': [{'name': 'Pod 详情 YAML',
             'desc': 'Pod 完整描述',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get pod {POD} -n {NAMESPACE} -o yaml',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/pods/{POD}'},
            {'name': 'Pod 事件',
             'desc': 'Pod Events',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get events -n {NAMESPACE} --field-selector involvedObject.name={POD}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/events'},
            {'name': 'Pod 日志',
             'desc': '容器日志',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl logs {POD} -n {NAMESPACE} --tail=100',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/pods/{POD}/log?tailLines=100'},
            {'name': 'Secret 详情',
             'desc': 'Secret YAML',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get secret {SECRET} -n {NAMESPACE} -o yaml',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/secrets/{SECRET}'},
            {'name': 'Node 详情',
             'desc': 'Node 描述',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl describe node {NODE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/nodes/{NODE}'},
            {'name': 'Deployment 详情',
             'desc': 'Deployment YAML',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get deployment {DEPLOYMENT} -n {NAMESPACE} -o yaml',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/apps/v1/namespaces/{NAMESPACE}/deployments/{DEPLOYMENT}'},
            {'name': 'Pod 前一容器日志',
             'desc': 'previous log',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl logs {POD} -n {NAMESPACE} --previous --tail=50',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '"{APISERVER}/api/v1/namespaces/{NAMESPACE}/pods/{POD}/log?previous=true&tailLines=50"'},
            {'name': 'describe Pod',
             'desc': 'Pod 事件详情',
             'tags': ['k8s_conn', 'target'],
             'exec': 'kubectl',
             'kubectl': 'kubectl describe pod {POD} -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/pods/{POD}'},
            {'name': 'Lease 协调锁',
             'desc': 'Lease 对象',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get lease -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/coordination.k8s.io/v1/namespaces/{NAMESPACE}/leases'}]},
 {'category': '🚪 进入容器',
  'items': [{'name': 'exec 进入 Pod',
             'desc': 'kubectl exec 交互 shell',
             'tags': ['k8s_conn', 'target'],
             'exec': 'kubectl',
             'kubectl': 'kubectl exec -it {POD} -n {NAMESPACE} -- /bin/sh',
             'curl': '# exec 仅 kubectl 模式'},
            {'name': 'exec 指定容器',
             'desc': '多容器 Pod exec',
             'tags': ['k8s_conn', 'target'],
             'exec': 'kubectl',
             'kubectl': 'kubectl exec -it {POD} -n {NAMESPACE} -c {CONTAINER} -- /bin/sh',
             'curl': '# exec 仅 kubectl 模式'},
            {'name': 'port-forward Pod',
             'desc': '端口转发到本地',
             'tags': ['k8s_conn', 'target'],
             'exec': 'kubectl',
             'kubectl': 'kubectl port-forward pod/{POD} {LOCAL_PORT}:{REMOTE_PORT} -n {NAMESPACE}',
             'curl': '# port-forward 仅 kubectl 模式'},
            {'name': 'port-forward Service',
             'desc': 'Service 端口转发',
             'tags': ['k8s_conn', 'target'],
             'exec': 'kubectl',
             'kubectl': 'kubectl port-forward svc/{SERVICE} {LOCAL_PORT}:{REMOTE_PORT} -n {NAMESPACE}',
             'curl': '# port-forward 仅 kubectl 模式'}]},
 {'category': '🔎 容器内自查',
  'items': [{'name': '读取 SA Token',
             'desc': 'cat SA token 路径',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'cat /var/run/secrets/kubernetes.io/serviceaccount/token',
             'curl': 'cat /var/run/secrets/kubernetes.io/serviceaccount/token'},
            {'name': '读取 SA CA',
             'desc': 'cat CA cert',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt',
             'curl': 'cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt'},
            {'name': '检测 /.dockerenv',
             'desc': 'Docker 容器标志',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'test -f /.dockerenv && echo IN_DOCKER || echo NOT_DOCKER',
             'curl': 'test -f /.dockerenv && echo IN_DOCKER || echo NOT_DOCKER'},
            {'name': '检测 cgroup',
             'desc': 'cgroup 容器检测',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'cat /proc/1/cgroup 2>/dev/null | head -5',
             'curl': 'cat /proc/1/cgroup 2>/dev/null | head -5'},
            {'name': '环境变量 dump',
             'desc': 'printenv 敏感排查',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'printenv | sort',
             'curl': 'printenv | sort'},
            {'name': '挂载点列表',
             'desc': 'mount 信息',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'mount | head -30',
             'curl': 'mount | head -30'},
            {'name': '网络连接',
             'desc': 'ss/netstat',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'ss -tlnp 2>/dev/null || netstat -tlnp 2>/dev/null',
             'curl': 'ss -tlnp 2>/dev/null || netstat -tlnp 2>/dev/null'},
            {'name': '进程列表',
             'desc': 'ps aux',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'ps aux',
             'curl': 'ps aux'},
            {'name': '可读 /etc/passwd',
             'desc': '用户枚举',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'cat /etc/passwd 2>/dev/null | head -20',
             'curl': 'cat /etc/passwd 2>/dev/null | head -20'},
            {'name': 'capabilities',
             'desc': 'capsh 检查',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'capsh --print 2>/dev/null || cat /proc/self/status | grep Cap',
             'curl': 'capsh --print 2>/dev/null || cat /proc/self/status | grep Cap'},
            {'name': 'service account 目录',
             'desc': 'SA 挂载',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'ls -la /var/run/secrets/kubernetes.io/serviceaccount/ 2>/dev/null',
             'curl': 'ls -la /var/run/secrets/kubernetes.io/serviceaccount/ 2>/dev/null'},
            {'name': 'DNS resolv.conf',
             'desc': 'DNS 配置',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'cat /etc/resolv.conf',
             'curl': 'cat /etc/resolv.conf'},
            {'name': 'hosts 文件',
             'desc': '/etc/hosts',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'cat /etc/hosts',
             'curl': 'cat /etc/hosts'}]},
 {'category': '⚙️ 配置检查',
  'items': [{'name': '查看 LimitRange',
             'desc': '资源限制',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get limitrange -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/limitranges'},
            {'name': '查看 ResourceQuota',
             'desc': '配额',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get resourcequota -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/resourcequotas'},
            {'name': '查看 PodSecurityPolicy',
             'desc': 'PSP (旧版)',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get psp 2>/dev/null || echo N/A',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/policy/v1beta1/podsecuritypolicies'},
            {'name': '查看 MutatingWebhook',
             'desc': '变更 Webhook',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get mutatingwebhookconfigurations',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations'},
            {'name': '查看 ValidatingWebhook',
             'desc': '校验 Webhook',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get validatingwebhookconfigurations',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations'},
            {'name': '查看 CRD',
             'desc': '自定义资源',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get crd',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/apiextensions.k8s.io/v1/customresourcedefinitions'},
            {'name': '查看 PriorityClass',
             'desc': '优先级类',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get priorityclass',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/scheduling.k8s.io/v1/priorityclasses'},
            {'name': '查看 RuntimeClass',
             'desc': '运行时类',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get runtimeclass',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/node.k8s.io/v1/runtimeclasses'},
            {'name': '查看 StorageClass',
             'desc': '存储类',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get storageclass',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/storage.k8s.io/v1/storageclasses'},
            {'name': '查看 CSIDriver',
             'desc': 'CSI 驱动',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get csidrivers',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/storage.k8s.io/v1/csidrivers'},
            {'name': '查看 APIService',
             'desc': '聚合 API',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': 'kubectl get apiservices',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/apiregistration.k8s.io/v1/apiservices'},
            {'name': '查看 EndpointSlice',
             'desc': '端点切片',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get endpointslices -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/discovery.k8s.io/v1/namespaces/{NAMESPACE}/endpointslices'}]},
 {'category': '🌐 网络',
  'items': [{'name': 'NetworkPolicy 列表',
             'desc': 'NS NetworkPolicy',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get networkpolicy -n {NAMESPACE}',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/networking.k8s.io/v1/namespaces/{NAMESPACE}/networkpolicies'},
            {'name': 'CNI 配置目录',
             'desc': '本地 CNI',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'ls /etc/cni/net.d/ 2>/dev/null',
             'curl': 'ls /etc/cni/net.d/ 2>/dev/null'},
            {'name': 'kubelet 10250 探测',
             'desc': 'Node kubelet HTTPS',
             'tags': ['node', 'target'],
             'exec': 'curl',
             'kubectl': 'curl -sk https://{NODE_IP}:10250/healthz',
             'curl': 'curl -sk --max-time 3 https://{NODE_IP}:10250/healthz'},
            {'name': 'DNS 解析测试',
             'desc': '集群 DNS',
             'tags': ['local'],
             'exec': 'local',
             'kubectl': 'nslookup kubernetes.default.svc.cluster.local 2>/dev/null || getent hosts kubernetes.default',
             'curl': 'nslookup kubernetes.default.svc.cluster.local 2>/dev/null || getent hosts kubernetes.default'},
            {'name': 'Service ClusterIP',
             'desc': 'SVC 详情',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get svc {SERVICE} -n {NAMESPACE} -o yaml',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/{NAMESPACE}/services/{SERVICE}'},
            {'name': 'Ingress 详情',
             'desc': 'Ingress YAML',
             'tags': ['k8s_conn', 'target'],
             'exec': 'both',
             'kubectl': 'kubectl get ingress -n {NAMESPACE} -o yaml',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/apis/networking.k8s.io/v1/namespaces/{NAMESPACE}/ingresses'},
            {'name': 'API Server 健康',
             'desc': '/healthz',
             'tags': ['k8s_conn'],
             'exec': 'curl',
             'kubectl': 'curl -sk {APISERVER}/healthz',
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" {APISERVER}/healthz'},
            {'name': 'etcd 探测 (常见)',
             'desc': '2379 端口',
             'tags': ['node'],
             'exec': 'curl',
             'kubectl': 'curl -sk --max-time 2 https://{NODE_IP}:2379/health',
             'curl': 'curl -sk --max-time 2 https://{NODE_IP}:2379/health'},
            {'name': '集群 DNS 服务',
             'desc': 'kube-dns SVC',
             'tags': ['k8s_conn'],
             'exec': 'both',
             'kubectl': "kubectl get svc -n kube-system | grep -E 'dns|coredns'",
             'curl': 'curl -s {TLS} --cacert {CACERT} -H "Authorization: Bearer {TOKEN}" '
                     '{APISERVER}/api/v1/namespaces/kube-system/services'}]},
 {'category': '☁️ AWS (亚马逊云)',
  'items': [{'name': 'ECS 临时密钥 (示例 UUID)',
             'desc': 'Fargate/ECS 容器 169.254.170.2；UUID 变更请用 env 查看 AWS_CONTAINER_CREDENTIALS_RELATIVE_URI',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl 169.254.170.2/v2/credentials/16259826-e172-4870-a6f8-0ba9f9b7c7f9',
             'curl': 'curl 169.254.170.2/v2/credentials/16259826-e172-4870-a6f8-0ba9f9b7c7f9'},
            {'name': 'ECS 临时密钥 (环境变量)',
             'desc': 'curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI 自动读取最新有效路径',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI',
             'curl': 'curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI'},
            {'name': '查看 AWS 凭证 URI 变量',
             'desc': 'printenv AWS_CONTAINER_CREDENTIALS_RELATIVE_URI 等 ECS 相关变量',
             'tags': ['cloud', 'local'],
             'exec': 'local',
             'kubectl': "env | grep -E 'AWS_CONTAINER_CREDENTIALS|AWS_EXECUTION_ENV|AWS_DEFAULT_REGION|AWS_REGION|AWS_ROLE'",
             'curl': "env | grep -E 'AWS_CONTAINER_CREDENTIALS|AWS_EXECUTION_ENV|AWS_DEFAULT_REGION|AWS_REGION|AWS_ROLE'"},
            {'name': 'IMDSv1 元数据根',
             'desc': 'EC2 IMDSv1',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/latest/meta-data/',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/latest/meta-data/'},
            {'name': 'IAM Role 列表',
             'desc': '绑定 IAM Role',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/',
             'curl': 'curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/'},
            {'name': 'IAM 角色凭证',
             'desc': '替换 {ROLE_NAME}',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/{ROLE_NAME}',
             'curl': 'curl -s http://169.254.169.254/latest/meta-data/iam/security-credentials/{ROLE_NAME}'},
            {'name': 'IMDSv2 Token',
             'desc': 'PUT 获取 Token',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s -X PUT http://169.254.169.254/latest/api/token -H '
                        "'X-aws-ec2-metadata-token-ttl-seconds: 21600'",
             'curl': "curl -s -X PUT http://169.254.169.254/latest/api/token -H 'X-aws-ec2-metadata-token-ttl-seconds: "
                     "21600'"},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/latest/meta-data/instance-id',
             'curl': 'curl -s http://169.254.169.254/latest/meta-data/instance-id'}]},
 {'category': '🟢 GCP (谷歌云)',
  'items': [{'name': 'GCE 元数据根',
             'desc': 'GCP metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "curl -s --max-time 3 -H 'Metadata-Flavor: Google' "
                        'http://metadata.google.internal/computeMetadata/v1/',
             'curl': "curl -s --max-time 3 -H 'Metadata-Flavor: Google' "
                     'http://metadata.google.internal/computeMetadata/v1/'},
            {'name': 'GCE 项目 ID',
             'desc': 'project-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "curl -s -H 'Metadata-Flavor: Google' "
                        'http://metadata.google.internal/computeMetadata/v1/project/project-id',
             'curl': "curl -s -H 'Metadata-Flavor: Google' "
                     'http://metadata.google.internal/computeMetadata/v1/project/project-id'},
            {'name': 'GCE SA Token',
             'desc': '默认 SA token (metadata 固定路径)',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "curl -s -H 'Metadata-Flavor: Google' "
                        "'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token'",
             'curl': "curl -s -H 'Metadata-Flavor: Google' "
                     "'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token'"},
            {'name': 'GCE SA Token (指定 SA)',
             'desc': '替换 default 为 $GOOGLE_CLOUD_PROJECT 对应 SA 名，或 metadata 下列 SA 列表',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "SA=${GCE_METADATA_SA:-default} && curl -s -H 'Metadata-Flavor: Google' "
                        '"http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/${SA}/token"',
             'curl': "SA=${GCE_METADATA_SA:-default} && curl -s -H 'Metadata-Flavor: Google' "
                     '"http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/${SA}/token"'},
            {'name': '查看 GCP 元数据变量',
             'desc': 'env 查看 GOOGLE_CLOUD / GCP / GCE 相关变量',
             'tags': ['cloud', 'local'],
             'exec': 'local',
             'kubectl': "env | grep -iE 'GOOGLE_CLOUD|GCP_|GCE_|K_SERVICE|K_REVISION'",
             'curl': "env | grep -iE 'GOOGLE_CLOUD|GCP_|GCE_|K_SERVICE|K_REVISION'"},
            {'name': 'GKE 集群名',
             'desc': 'GKE cluster',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "curl -s -H 'Metadata-Flavor: Google' "
                        'http://metadata.google.internal/computeMetadata/v1/instance/attributes/cluster-name',
             'curl': "curl -s -H 'Metadata-Flavor: Google' "
                     'http://metadata.google.internal/computeMetadata/v1/instance/attributes/cluster-name'}]},
 {'category': '🚀 Cloud Run / Knative',
  'items': [{'name': '平台说明',
             'desc': 'Cloud Run = GCP 谷歌云 (Knative)',
             'tags': ['cloud', 'local'],
             'exec': 'local',
             'kubectl': 'echo "Google Cloud Run — 基于 Knative，属 GCP 谷歌云；元数据与 SA 见本分类下方命令"',
             'curl': 'echo "Google Cloud Run — 基于 Knative，属 GCP 谷歌云；元数据与 SA 见本分类下方命令"'},
            {'name': 'Knative 环境变量',
             'desc': 'K_SERVICE / K_REVISION / PORT / GCP 项目',
             'tags': ['cloud', 'local'],
             'exec': 'local',
             'kubectl': "env | grep -E '^(K_|PORT|GOOGLE_|GCP_|GCLOUD_|FUNCTION_|CLOUD_RUN_)' | sort",
             'curl': "env | grep -E '^(K_|PORT|GOOGLE_|GCP_|GCLOUD_|FUNCTION_|CLOUD_RUN_)' | sort"},
            {'name': 'Knative 服务摘要',
             'desc': '服务名、版本、配置、端口',
             'tags': ['cloud', 'local'],
             'exec': 'local',
             'kubectl': 'echo "service=$K_SERVICE revision=$K_REVISION config=$K_CONFIGURATION port=$PORT project=${GOOGLE_CLOUD_PROJECT:-$GCP_PROJECT}"',
             'curl': 'echo "service=$K_SERVICE revision=$K_REVISION config=$K_CONFIGURATION port=$PORT project=${GOOGLE_CLOUD_PROJECT:-$GCP_PROJECT}"'},
            {'name': 'GCP 元数据根',
             'desc': 'Cloud Run 同样走 GCP metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "curl -s --max-time 3 -H 'Metadata-Flavor: Google' "
                        'http://metadata.google.internal/computeMetadata/v1/',
             'curl': "curl -s --max-time 3 -H 'Metadata-Flavor: Google' "
                     'http://metadata.google.internal/computeMetadata/v1/'},
            {'name': 'GCP 项目 ID',
             'desc': 'project-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "curl -s -H 'Metadata-Flavor: Google' "
                        'http://metadata.google.internal/computeMetadata/v1/project/project-id',
             'curl': "curl -s -H 'Metadata-Flavor: Google' "
                     'http://metadata.google.internal/computeMetadata/v1/project/project-id'},
            {'name': 'GCP 区域',
             'desc': 'Cloud Run 部署区域',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "curl -s -H 'Metadata-Flavor: Google' "
                        'http://metadata.google.internal/computeMetadata/v1/instance/region',
             'curl': "curl -s -H 'Metadata-Flavor: Google' "
                     'http://metadata.google.internal/computeMetadata/v1/instance/region'},
            {'name': 'GCP SA Token',
             'desc': '默认服务账号 token',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "curl -s -H 'Metadata-Flavor: Google' "
                        "'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token'",
             'curl': "curl -s -H 'Metadata-Flavor: Google' "
                     "'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token'"},
            {'name': 'GCP 实例 ID',
             'desc': 'instance id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': "curl -s -H 'Metadata-Flavor: Google' "
                        'http://metadata.google.internal/computeMetadata/v1/instance/id',
             'curl': "curl -s -H 'Metadata-Flavor: Google' "
                     'http://metadata.google.internal/computeMetadata/v1/instance/id'}]},
 {'category': '🟠 阿里云',
  'items': [{'name': '元数据根',
             'desc': '100.100.100.200',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://100.100.100.200/latest/meta-data/',
             'curl': 'curl -s --max-time 3 http://100.100.100.200/latest/meta-data/'},
            {'name': 'IMDSv2 Token + 元数据',
             'desc': '先 PUT 取 token 再带 Header 请求',
             'tags': ['cloud'],
             'exec': 'local',
             'kubectl': "TOKEN=$(curl -s -X PUT 'http://100.100.100.200/latest/api/token' -H 'X-aliyun-ecs-metadata-token-ttl-seconds: 21600') && "
                        'curl -s -H "X-aliyun-ecs-metadata-token: $TOKEN" http://100.100.100.200/latest/meta-data/ | head -10',
             'curl': "TOKEN=$(curl -s -X PUT 'http://100.100.100.200/latest/api/token' -H 'X-aliyun-ecs-metadata-token-ttl-seconds: 21600') && "
                     'curl -s -H "X-aliyun-ecs-metadata-token: $TOKEN" http://100.100.100.200/latest/meta-data/ | head -10'},
            {'name': 'RAM Role 列表',
             'desc': 'RAM 角色',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.100.100.200/latest/meta-data/ram/security-credentials/',
             'curl': 'curl -s http://100.100.100.200/latest/meta-data/ram/security-credentials/'},
            {'name': 'RAM 凭证',
             'desc': '替换 {ROLE_NAME}',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.100.100.200/latest/meta-data/ram/security-credentials/{ROLE_NAME}',
             'curl': 'curl -s http://100.100.100.200/latest/meta-data/ram/security-credentials/{ROLE_NAME}'},
            {'name': 'RAM 凭证 (环境变量)',
             'desc': 'curl 元数据+$ALIBABA_CLOUD_ECS_RAM_ROLE；角色名变更请 env | grep ALIBABA_CLOUD',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.100.100.200/latest/meta-data/ram/security-credentials/$ALIBABA_CLOUD_ECS_RAM_ROLE',
             'curl': 'curl -s http://100.100.100.200/latest/meta-data/ram/security-credentials/$ALIBABA_CLOUD_ECS_RAM_ROLE'},
            {'name': '查看阿里云 RAM 变量',
             'desc': 'printenv ALIBABA_CLOUD_ECS_RAM_ROLE 等',
             'tags': ['cloud', 'local'],
             'exec': 'local',
             'kubectl': "env | grep -E 'ALIBABA_CLOUD|ALIBABA_|ECS_RAM'",
             'curl': "env | grep -E 'ALIBABA_CLOUD|ALIBABA_|ECS_RAM'"},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.100.100.200/latest/meta-data/instance-id',
             'curl': 'curl -s http://100.100.100.200/latest/meta-data/instance-id'}]},
 {'category': '🔵 腾讯云',
  'items': [{'name': '元数据根',
             'desc': 'tencentyun metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://metadata.tencentyun.com/latest/meta-data/',
             'curl': 'curl -s --max-time 3 http://metadata.tencentyun.com/latest/meta-data/'},
            {'name': 'CAM Role 列表',
             'desc': 'CAM 角色',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://metadata.tencentyun.com/latest/meta-data/cam/security-credentials/',
             'curl': 'curl -s http://metadata.tencentyun.com/latest/meta-data/cam/security-credentials/'},
            {'name': 'CAM 凭证',
             'desc': '替换 {ROLE_NAME}',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://metadata.tencentyun.com/latest/meta-data/cam/security-credentials/{ROLE_NAME}',
             'curl': 'curl -s http://metadata.tencentyun.com/latest/meta-data/cam/security-credentials/{ROLE_NAME}'},
            {'name': 'CAM 凭证 (环境变量)',
             'desc': '先 CAM Role 列表获角色名，或 env 查看 TKE/容器注入的 CAM 相关变量后替换 $ROLE',
             'tags': ['cloud'],
             'exec': 'local',
             'kubectl': "ROLE=$(curl -s http://metadata.tencentyun.com/latest/meta-data/cam/security-credentials/ | head -1) && "
                        'curl -s http://metadata.tencentyun.com/latest/meta-data/cam/security-credentials/$ROLE',
             'curl': "ROLE=$(curl -s http://metadata.tencentyun.com/latest/meta-data/cam/security-credentials/ | head -1) && "
                     'curl -s http://metadata.tencentyun.com/latest/meta-data/cam/security-credentials/$ROLE'},
            {'name': '查看腾讯云 CAM 变量',
             'desc': 'env 查看 TENCENT/CAM/容器注入凭证相关变量',
             'tags': ['cloud', 'local'],
             'exec': 'local',
             'kubectl': "env | grep -iE 'TENCENT|CAM|SECRET|CREDENTIAL'",
             'curl': "env | grep -iE 'TENCENT|CAM|SECRET|CREDENTIAL'"},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://metadata.tencentyun.com/latest/meta-data/instance-id',
             'curl': 'curl -s http://metadata.tencentyun.com/latest/meta-data/instance-id'}]},
 {'category': '🔴 华为云',
  'items': [{'name': '元数据根',
             'desc': '华为云 metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/latest/meta-data/',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/latest/meta-data/'},
            {'name': 'Agency 列表',
             'desc': 'IAM Agency',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/openstack/latest/securitykey',
             'curl': 'curl -s http://169.254.169.254/openstack/latest/securitykey'},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/latest/meta-data/instance-id',
             'curl': 'curl -s http://169.254.169.254/latest/meta-data/instance-id'},
            {'name': '区域',
             'desc': 'placement/region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/latest/meta-data/placement/region',
             'curl': 'curl -s http://169.254.169.254/latest/meta-data/placement/region'}]},
 {'category': '🔷 Azure (微软云)',
  'items': [{'name': 'IMDS 根',
             'desc': 'Azure IMDS',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 -H Metadata:true '
                        "'http://169.254.169.254/metadata/instance?api-version=2021-02-01'",
             'curl': 'curl -s --max-time 3 -H Metadata:true '
                     "'http://169.254.169.254/metadata/instance?api-version=2021-02-01'"},
            {'name': 'Azure 订阅',
             'desc': 'subscriptionId',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s -H Metadata:true '
                        "'http://169.254.169.254/metadata/instance/compute/subscriptionId?api-version=2021-02-01&format=text'",
             'curl': 'curl -s -H Metadata:true '
                     "'http://169.254.169.254/metadata/instance/compute/subscriptionId?api-version=2021-02-01&format=text'"},
            {'name': 'Managed Identity Token',
             'desc': 'MI token (IMDS 固定路径)',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s -H Metadata:true '
                        "'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/'",
             'curl': 'curl -s -H Metadata:true '
                     "'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/'"},
            {'name': 'Managed Identity (环境变量)',
             'desc': 'AKS/Container Apps：curl $IDENTITY_ENDPOINT 并带 IDENTITY_HEADER',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s "$IDENTITY_ENDPOINT?api-version=2019-08-01&resource=https://management.azure.com/" '
                        '-H "Metadata: true" -H "X-Identity-Header: $IDENTITY_HEADER"',
             'curl': 'curl -s "$IDENTITY_ENDPOINT?api-version=2019-08-01&resource=https://management.azure.com/" '
                     '-H "Metadata: true" -H "X-Identity-Header: $IDENTITY_HEADER"'},
            {'name': '查看 Azure Identity 变量',
             'desc': 'printenv IDENTITY_ENDPOINT / IDENTITY_HEADER 等',
             'tags': ['cloud', 'local'],
             'exec': 'local',
             'kubectl': "env | grep -iE 'IDENTITY_|AZURE_|MSI_|IMDS'",
             'curl': "env | grep -iE 'IDENTITY_|AZURE_|MSI_|IMDS'"},
            {'name': 'VM 名称',
             'desc': 'name',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s -H Metadata:true '
                        "'http://169.254.169.254/metadata/instance/compute/name?api-version=2021-02-01&format=text'",
             'curl': 'curl -s -H Metadata:true '
                     "'http://169.254.169.254/metadata/instance/compute/name?api-version=2021-02-01&format=text'"}]},
 {'category': '🟡 百度云',
  'items': [{'name': '元数据根',
             'desc': 'BCE metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/v1/meta-data/',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/v1/meta-data/'},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/v1/meta-data/instance-id',
             'curl': 'curl -s http://169.254.169.254/v1/meta-data/instance-id'},
            {'name': '区域',
             'desc': 'zone',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/v1/meta-data/zone',
             'curl': 'curl -s http://169.254.169.254/v1/meta-data/zone'}]},
 {'category': '🟣 Oracle OCI',
  'items': [{'name': 'OCI 元数据',
             'desc': 'instance metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 -H "Authorization: Bearer Oracle" '
                        'http://169.254.169.254/opc/v2/instance/',
             'curl': 'curl -s --max-time 3 -H "Authorization: Bearer Oracle" '
                     'http://169.254.169.254/opc/v2/instance/'},
            {'name': 'OCI 身份',
             'desc': 'identity',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/opc/v2/identity/',
             'curl': 'curl -s http://169.254.169.254/opc/v2/identity/'},
            {'name': 'OCI 区域',
             'desc': 'region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/opc/v2/instance/region',
             'curl': 'curl -s http://169.254.169.254/opc/v2/instance/region'}]},
 {'category': '🌊 DigitalOcean',
  'items': [{'name': 'DO 元数据',
             'desc': 'droplet metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/metadata/v1/',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/metadata/v1/'},
            {'name': 'DO ID',
             'desc': 'id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/metadata/v1/id',
             'curl': 'curl -s http://169.254.169.254/metadata/v1/id'},
            {'name': 'DO 区域',
             'desc': 'region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/metadata/v1/region',
             'curl': 'curl -s http://169.254.169.254/metadata/v1/region'}]},
 {'category': '🟩 Linode',
  'items': [{'name': 'Linode 元数据',
             'desc': 'linode metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/v4/',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/v4/'},
            {'name': 'Linode ID',
             'desc': 'id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/v4/id',
             'curl': 'curl -s http://169.254.169.254/v4/id'},
            {'name': 'Linode 区域',
             'desc': 'region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/v4/region',
             'curl': 'curl -s http://169.254.169.254/v4/region'}]},
 {'category': '⚡ Vultr',
  'items': [{'name': 'Vultr 元数据',
             'desc': 'vultr metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/v1/',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/v1/'},
            {'name': 'Vultr ID',
             'desc': 'id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/v1/id',
             'curl': 'curl -s http://169.254.169.254/v1/id'},
            {'name': 'Vultr 区域',
             'desc': 'region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/v1/region',
             'curl': 'curl -s http://169.254.169.254/v1/region'}]},
 {'category': '🔶 IBM Cloud',
  'items': [{'name': 'IBM 元数据',
             'desc': 'ibm metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/opc/v1/instance/',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/opc/v1/instance/'},
            {'name': 'IBM 身份',
             'desc': 'identity',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/opc/v1/identity/',
             'curl': 'curl -s http://169.254.169.254/opc/v1/identity/'},
            {'name': 'IBM 区域',
             'desc': 'region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/opc/v1/instance/region',
             'curl': 'curl -s http://169.254.169.254/opc/v1/instance/region'}]},
 {'category': '🟤 金山云',
  'items': [{'name': 'KSY 元数据',
             'desc': 'ksyun metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://100.100.100.200/latest/meta-data/',
             'curl': 'curl -s --max-time 3 http://100.100.100.200/latest/meta-data/'},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.100.100.200/latest/meta-data/instance-id',
             'curl': 'curl -s http://100.100.100.200/latest/meta-data/instance-id'},
            {'name': '区域',
             'desc': 'region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.100.100.200/latest/meta-data/placement/region',
             'curl': 'curl -s http://100.100.100.200/latest/meta-data/placement/region'}]},
 {'category': '🔹 UCloud',
  'items': [{'name': 'UCloud 元数据',
             'desc': 'ucloud metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://100.64.0.1/meta-data/',
             'curl': 'curl -s --max-time 3 http://100.64.0.1/meta-data/'},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.64.0.1/meta-data/instance-id',
             'curl': 'curl -s http://100.64.0.1/meta-data/instance-id'},
            {'name': '区域',
             'desc': 'region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.64.0.1/meta-data/region',
             'curl': 'curl -s http://100.64.0.1/meta-data/region'}]},
 {'category': '🛒 京东云',
  'items': [{'name': 'JD 元数据',
             'desc': 'jdcloud metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/latest/meta-data/',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/latest/meta-data/'},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/latest/meta-data/instance-id',
             'curl': 'curl -s http://169.254.169.254/latest/meta-data/instance-id'},
            {'name': '区域',
             'desc': 'placement/region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/latest/meta-data/placement/region',
             'curl': 'curl -s http://169.254.169.254/latest/meta-data/placement/region'}]},
 {'category': '🌋 火山引擎',
  'items': [{'name': 'Volc 元数据',
             'desc': 'volcengine metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://100.96.0.96/volcstack/latest/meta-data/',
             'curl': 'curl -s --max-time 3 http://100.96.0.96/volcstack/latest/meta-data/'},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.96.0.96/volcstack/latest/meta-data/instance-id',
             'curl': 'curl -s http://100.96.0.96/volcstack/latest/meta-data/instance-id'},
            {'name': '区域',
             'desc': 'region',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://100.96.0.96/volcstack/latest/meta-data/placement/region',
             'curl': 'curl -s http://100.96.0.96/volcstack/latest/meta-data/placement/region'}]},
 {'category': '☁️ 青云 QingCloud',
  'items': [{'name': 'QC 元数据',
             'desc': 'qingcloud metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/latest/meta-data/',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/latest/meta-data/'},
            {'name': '实例 ID',
             'desc': 'instance-id',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/latest/meta-data/instance-id',
             'curl': 'curl -s http://169.254.169.254/latest/meta-data/instance-id'},
            {'name': '区域',
             'desc': 'zone',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/latest/meta-data/placement/zone',
             'curl': 'curl -s http://169.254.169.254/latest/meta-data/placement/zone'}]},
 {'category': '🏗️ OpenStack',
  'items': [{'name': 'OpenStack 元数据',
             'desc': 'openstack metadata',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s --max-time 3 http://169.254.169.254/openstack/latest/meta_data.json',
             'curl': 'curl -s --max-time 3 http://169.254.169.254/openstack/latest/meta_data.json'},
            {'name': 'OpenStack 用户数据',
             'desc': 'user_data',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/openstack/latest/user_data',
             'curl': 'curl -s http://169.254.169.254/openstack/latest/user_data'},
            {'name': 'OpenStack 网络',
             'desc': 'network_data',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/openstack/latest/network_data.json',
             'curl': 'curl -s http://169.254.169.254/openstack/latest/network_data.json'},
            {'name': 'OpenStack 密钥',
             'desc': 'securitykey',
             'tags': ['cloud'],
             'exec': 'curl',
             'kubectl': 'curl -s http://169.254.169.254/openstack/latest/securitykey',
             'curl': 'curl -s http://169.254.169.254/openstack/latest/securitykey'}]}]

CATEGORY_INDEX = {'☁️ AWS (亚马逊云)': ('云平台', 0),
 '☁️ 青云 QingCloud': ('云平台', 17),
 '🚀 Cloud Run / Knative': ('云平台', 2),
 '⚙️ 配置检查': ('K8s', 5),
 '⚡ Vultr': ('云平台', 11),
 '🌊 DigitalOcean': ('云平台', 9),
 '🌋 火山引擎': ('云平台', 16),
 '🌐 网络': ('K8s', 6),
 '📋 快速自查': ('环境识别', 0),
 '🐧 Linux 探测': ('环境识别', 1),
 '🪟 Windows 探测': ('环境识别', 2),
 '☸️ K8s API 探测': ('环境识别', 3),
 '🏗️ OpenStack': ('云平台', 18),
 '📋 详情与日志': ('K8s', 2),
 '🔍 查看资源': ('K8s', 0),
 '🔎 容器内自查': ('K8s', 4),
 '🔑 权限与身份': ('K8s', 1),
 '🔴 华为云': ('云平台', 5),
 '🔵 腾讯云': ('云平台', 4),
 '🔶 IBM Cloud': ('云平台', 12),
 '🔷 Azure (微软云)': ('云平台', 6),
 '🔹 UCloud': ('云平台', 14),
 '🚪 进入容器': ('K8s', 3),
 '🛒 京东云': ('云平台', 15),
 '🟠 阿里云': ('云平台', 3),
 '🟡 百度云': ('云平台', 7),
 '🟢 GCP (谷歌云)': ('云平台', 1),
 '🟣 Oracle OCI': ('云平台', 8),
 '🟤 金山云': ('云平台', 13),
 '🟩 Linode': ('云平台', 10)}
